### ISSUE TITLE
Fix map mapping function

### ISSUE THREAD

**Issue by jeremie-j** [StryderDev/ApexStats#45]
https://github.com/StryderDev/ApexStats/blob/fb578371e22d53504b20a8ece73dc7ab5e1a26e7/src/slash/utilities/drop.js#L34
Shouldn't it be
```if (map == 'Broken Moon') return 'Broken_Moon';```
instead ?

**Comment by SDCore** [comment]
You are so right. Appreciate you bringing it to my attention 👍🏻
